import Head from "next/head";
import Header from "../Components/Header/Header";
import Nav from "../Components/Nav/Nav";
import Row from "../Components/Row/Row";
import Pagination from "../Components/Pagination/Pagination";
import requests from "../Requests/requests";


export default function Home({ results }) {
  console.log(results);
  return (
    <div className="reletive flex flex-col gap-3 bg-black">
      <Head>
        <title>Hulu Clone - therogersak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Row results={results} />
      <Pagination />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const current = context.query.current;
  const page = context.query.page

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[current ||  genre]?.url || requests.fetchActionMovies.url
    }&page=${page}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
